# Generated by Django 4.2.5 on 2023-10-30 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True, verbose_name='Nombre diagnostico')),
                ('foto_pieza', models.ImageField(blank=True, null=True, upload_to='imagen_pieza/')),
                ('tiempo_instalacion', models.CharField(max_length=50, null=True, verbose_name='Tiempo de instalacion')),
                ('recomendacion', models.CharField(max_length=50, null=True, verbose_name='Recomendación')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Costo de la pieza')),
                ('descripcion', models.TextField(verbose_name='Descripción del diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('caracteristicas_posibles', models.TextField(verbose_name='Características posibles')),
                ('caracteristicas_reales', models.TextField(blank=True, null=True, verbose_name='Características reales')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del hallazgo')),
                ('descripcion', models.TextField(verbose_name='Descripción del hallazgo')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, null=True, verbose_name='Folio')),
                ('fecha_recibo', models.DateField(null=True, verbose_name='Fecha de recepción')),
                ('fecha_entrega', models.DateField(default=None, verbose_name='Fecha de entrega')),
                ('costo_aproximado', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Costo aproximado')),
                ('costo_final', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo final')),
                ('descripcion_cliente', models.TextField(null=True, verbose_name='Descripción del cleinte')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.etapa')),
            ],
        ),
    ]
